#ifndef TEST_MICPOD_H__
#define TEST_MICPOD_H__

#include "xparameters.h"
#include "xil_types.h"

//Bus definition


#define RX_BUS_ADDR					XPAR_TDM_HUB_0_RX_DATA_BRAM_CTRL_S_AXI_BASEADDR

#define TX_BUS_ADDR					XPAR_TDM_HUB_0_TX_DATA_BRAM_CTRL_S_AXI_BASEADDR

#define COMM_BUS_ADDR				XPAR_TDM_HUB_0_COMM_MANAGER_BASEADDR

#define RX_BUS_INTR_ID				XPAR_FABRIC_TDM_HUB_0_COMM_MANAGER_INTR0_INTR


#define BUS_ROUTER_BASE_ADDR		XPAR_BUS_ROUTER_MIC_POD_HUB_BASEADDR

#define GPIOS_ID					XPAR_XGPIOPS_0_DEVICE_ID
#define LED_OFFSET					54



#define AUDIO_ROUTING_REG_ADDR		XPAR_AUDIO_ROUTER_BASEADDR
#define AUDIO_CH_NUMBER				15
#endif
