//****************************************************************************************
// This file is generated by the MCHP build process and is included inside I_MCHP.hpp		
// to properly build it within the calling application: PLEASE DO NOT EDIT.				
//****************************************************************************************
 
#define CUSTOM bdSound/Bolide
 
#define SAMPLE_FREQ			32000
#define FRAME_TIME			8
#define SUB_FRAME_TIME		8
 
#define _ADAPT_DELAY_			0

#define _DMVDR_ENDFIRE_		1
#define _DMVDR_BROADSIDE_		0
#define _NDMVDR_				0
#define _XPDMVDR_				0
#define _SDMVDR_				1

#define EXT_NUM_MICS			0

#define _DMVDR_		(_DMVDR_ENDFIRE_ || _DMVDR_BROADSIDE_ || _NDMVDR_ || _XPDMVDR_ || _SDMVDR_)

#define _BEAMFORMING_			_DMVDR_

#define _DMVDR_ABM_			0

#if _DMVDR_
	#define DMVDR_NUM_MICS		2

	#if _XPDMVDR_ || _SDMVDR_
		#define BEAM_NUM_MICS	4
	#elif _NDMVDR_
		#ifndef BEAM_NUM_MICS
		#define BEAM_NUM_MICS	3
		#endif
	#else
		#define BEAM_NUM_MICS	DMVDR_NUM_MICS
	#endif

	#define NUMBER_OF_MICS	(BEAM_NUM_MICS + EXT_NUM_MICS)

	#if _XPDMVDR_
		#define NUMBER_OF_BEAMS 4
	#elif _SDMVDR_
		#define NUMBER_OF_BEAMS 8
	#elif _DMVDR_ENDFIRE_ && _DMVDR_BROADSIDE_
		#define NUMBER_OF_BEAMS (DMVDR_NUM_MICS+1)
	#elif _DMVDR_ENDFIRE_
		#define NUMBER_OF_BEAMS DMVDR_NUM_MICS
	#elif _DMVDR_BROADSIDE_
		#define NUMBER_OF_BEAMS 1
	#endif

	#define STEER_NUM_OUTS		(NUMBER_OF_BEAMS + EXT_NUM_MICS)
#else
	#define NUMBER_OF_MICS		1

	#define STEER_NUM_OUTS		NUMBER_OF_MICS
#endif

#define _MIC_STEERING_		(STEER_NUM_OUTS>1)
