//****************************************************************************************
// This file is generated by the MCHP build process and is included inside MCHP_API.hpp	
// to properly build it within the calling application: PLEASE DO NOT EDIT.				
//****************************************************************************************
 
#define _FS_8000_ 1
#define _FS_16000_ 1
#define _FS_24000_ 1
#define _FS_32000_ 1
#define _FS_44100_ 1
#define _FS_48000_ 1

#define _RX_IIR_BIQUAD_ 1
#define _RX_MBPL_ 0
#define _RX_LIMITER_ 1
#define _PARAM_EQ_ 1
#define _ADAPT_DELAY_ 0
#define _ADAPT_DELAY_MAX_ANDROID 0

#define _ENDFIRE_ARRAY_ 0

#define _BEAMFORMING_	(_ENDFIRE_ARRAY_)
#define _BEAM_ADAPTIVE_	0

#if _ENDFIRE_ARRAY_
#define NUMBER_OF_MICS 2
#elif !defined(NUMBER_OF_MICS)
#define NUMBER_OF_MICS 1
#endif
