#ifndef TEST_MICPOD_H__
#define TEST_MICPOD_H__

#include "xparameters.h"
#include "xil_types.h"

//Bus definition


#define RX_BUS_ADDR					XPAR_TDM_HUB_RX_DATA_BRAM_CTRL_S_AXI_BASEADDR

#define TX_BUS_ADDR					XPAR_TDM_HUB_TX_DATA_BRAM_CTRL_S_AXI_BASEADDR

#define COMM_BUS_ADDR				XPAR_TDM_HUB_COMM_MANAGER_BASEADDR

#define RX_BUS_INTR_ID				XPAR_FABRIC_TDM_HUB_COMM_MANAGER_INTR0_INTR


#define BUS_ROUTER_BASE_ADDR		XPAR_BUS_ROUTER_BASEADDR

#define GPIOS_ID					XPAR_XGPIOPS_0_DEVICE_ID
#define LED_OFFSET					54
#define RST_OFFSET					62
#define MUTE_OFFSET					64

#define AUDIO_TO_PS_MEM				XPAR_AUDIO_MIC_BRAM_CTRL_TO_PS_S_AXI_BASEADDR
#define AUDIO_TO_PS_REG				XPAR_AUDIO_MIC_AUDIO_TO_PS_BASEADDR
#define AUDIO_TO_PS_INTR			XPAR_FABRIC_AUDIO_MIC_AUDIO_TO_PS_INTR_INTR

#define AUDIO_FROM_PS_MEM			XPAR_AUDIO_MIC_BRAM_CTRL_FROM_PS_S_AXI_BASEADDR
#define AUDIO_FROM_PS_REG			XPAR_AUDIO_MIC_AUDIO_FROM_PS_BASEADDR
#define AUDIO_FROM_PS_INTR			XPAR_FABRIC_AUDIO_MIC_AUDIO_FROM_PS_INTR_INTR

#define AUDIO_ROUTING_REG_ADDR		XPAR_AUDIO_ROUTER_BASEADDR
#define AUDIO_CH_NUMBER				15
#endif
