




set_property PACKAGE_PIN M9 [get_ports BUFFER_2_TX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_2_TX]
set_property PACKAGE_PIN R13 [get_ports BUFFER_3_TX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_3_TX]
set_property PACKAGE_PIN H14 [get_ports BUFFER_2_RX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_2_RX]
set_property PACKAGE_PIN N7 [get_ports BUFFER_3_RX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_3_RX]
set_property PACKAGE_PIN M11 [get_ports BUFFER_2_DIR]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_2_DIR]
set_property PACKAGE_PIN R7 [get_ports BUFFER_3_DIR]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_3_DIR]
set_property PACKAGE_PIN R12 [get_ports PLL_LOCK]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_LOCK]
set_property PACKAGE_PIN P14 [get_ports {LEDS_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_OUT[3]}]
set_property PACKAGE_PIN L12 [get_ports PLL_WCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_WCLK]
set_property PACKAGE_PIN N11 [get_ports MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK]
set_property PACKAGE_PIN R15 [get_ports PLL_SPI_CS]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_SPI_CS]
set_property PACKAGE_PIN G11 [get_ports BUFFER_4_TX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_4_TX]
set_property PACKAGE_PIN P15 [get_ports PLL_SPI_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_SPI_SCLK]
set_property PACKAGE_PIN G12 [get_ports BUFFER_4_RX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_4_RX]
set_property PACKAGE_PIN P11 [get_ports PLL_SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports PLL_SPI_MOSI]
set_property PACKAGE_PIN N8 [get_ports {LEDS_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_OUT[2]}]
set_property PACKAGE_PIN K15 [get_ports BUFFER_5_TX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_5_TX]
set_property PACKAGE_PIN J14 [get_ports BUFFER_5_RX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_5_RX]
set_property PACKAGE_PIN P8 [get_ports BUFFER_0_TX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_0_TX]
set_property PACKAGE_PIN P9 [get_ports BUFFER_1_TX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_1_TX]
set_property PACKAGE_PIN R10 [get_ports BUFFER_0_RX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_0_RX]
set_property PACKAGE_PIN N9 [get_ports BUFFER_1_RX]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_1_RX]
set_property PACKAGE_PIN K11 [get_ports BUFFER_0_DIR]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_0_DIR]
set_property PACKAGE_PIN M14 [get_ports BUFFER_1_DIR]
set_property IOSTANDARD LVCMOS33 [get_ports BUFFER_1_DIR]
set_property PACKAGE_PIN R8 [get_ports {LEDS_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_OUT[0]}]
set_property PACKAGE_PIN L13 [get_ports {LEDS_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_OUT[1]}]


create_clock -period 61.035 -name MCLK [get_ports MCLK]


set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_16_384M_to_20_48M/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_phases/inst/plle2_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_phases/inst/plle2_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_phases/inst/plle2_adv_inst/CLKOUT2]]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_phases/inst/plle2_adv_inst/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_16_384M_to_20_48M/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_16_384M_to_20_48M/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_phases/inst/plle2_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_phases/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_phases/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins splitter_design_i/clock_gen/clk_16_384M_to_20_48M/inst/mmcm_adv_inst/CLKOUT0]]
